// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7Hzta06H1BCUfPH98pEfyjBW2slrQJ0',
    appId: '1:14464332273:web:2b21d6a364e45afaa4d450',
    messagingSenderId: '14464332273',
    projectId: 'flutter-chat-app-8fcea',
    authDomain: 'flutter-chat-app-8fcea.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8fcea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3D2xbAe_t7xfY1ZcZSh66CJd9gu4jY0U',
    appId: '1:14464332273:android:85ca0d05bbb3e7bea4d450',
    messagingSenderId: '14464332273',
    projectId: 'flutter-chat-app-8fcea',
    storageBucket: 'flutter-chat-app-8fcea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9jY6AiQNq3CjBkPmUv9VzdYFbY__chw',
    appId: '1:14464332273:ios:80b0192321172461a4d450',
    messagingSenderId: '14464332273',
    projectId: 'flutter-chat-app-8fcea',
    storageBucket: 'flutter-chat-app-8fcea.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv9jY6AiQNq3CjBkPmUv9VzdYFbY__chw',
    appId: '1:14464332273:ios:80b0192321172461a4d450',
    messagingSenderId: '14464332273',
    projectId: 'flutter-chat-app-8fcea',
    storageBucket: 'flutter-chat-app-8fcea.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV7Hzta06H1BCUfPH98pEfyjBW2slrQJ0',
    appId: '1:14464332273:web:6e8a2ba5bc8f30ffa4d450',
    messagingSenderId: '14464332273',
    projectId: 'flutter-chat-app-8fcea',
    authDomain: 'flutter-chat-app-8fcea.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8fcea.firebasestorage.app',
  );

}